### PR TITLE
Analytic operators

### PR DESCRIPTION
**Pull request by hadrienk**
We reworked the analytic engine to support operations on datasets. 

@pengfei99 I see a bunch of tests failing because of syntax/incorrect assertions. Could you take a pass and correct what you see is an easy fix? 

All the tests are in fr.insee.vtl.spark.processing.engine.analytic

### CODE REVIEW

**Comment by pengfei99** [comment]
@hadrienk I think the problems are not just the simple incorrect assertions. I noticed two types of errors

- **sytanx errors**: I think all the unit tests which contains `range between` are failed. Is there an update on VTL grammar?

For example, the below VTL syntax is no longer valid
```text
res := stddev_samp ( ds1 over ( partition by Id_1 order by Year range between -1 and 1) );
```

The unit test output:
```text 
fr.insee.vtl.model.exceptions.VtlScriptException: no viable alternative at input '-1 and'
```


- Precisions on decimal number: I commit a fix which only changes the assert case, but I think the better solution is to write another assert function which can round all the decimal numbers of the actual dataset then compare with the expected dataset

**Comment by NicoLaval** [comment]
@pengfei99 I think you forgot `preceding` or `following` keyword

**Comment by NicoLaval** [comment]
```
res := stddev_samp ( ds1 over ( partition by Id_1 order by Year range between -1 preceding and 1 following) );
```

Is VTL valid (you can validate your expressions [here](https://making-sense-info.github.io/ANTLR-Editor/?path=/story/vtleditor--default))

**Review by NicoLaval — APPROVED** [review]

**Comment by FranckCo** [comment]
See issue #300 for quality gate failing reason.

**Pull request merged**
